-- AlterTable
ALTER TABLE `Reserva` ADD COLUMN `lembrete1HoraEnviado` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lembrete3HorasEnviado` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lembrete6HorasEnviado` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `lembreteUmDiaEnviado` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `status` ENUM('PENDENTE', 'AGUARDANDO_APROVACAO', 'CANCELADO', 'RESERVADO', 'EM_FILA', 'OFERECIDO_LOCATARIO', 'BLOQUEADO') NOT NULL DEFAULT 'PENDENTE';
